const scuse = [
    "Stiamo ancora valutando le opzioni… dal 2010.",
    "Il fax si è inceppato proprio mentre firmavamo il contratto!",
    "Il giocatore ha detto di sì, ma poi ha visto l’hotel e ha cambiato idea.",
    "Abbiamo finito i soldi perché abbiamo rinnovato la panchina della squadra.",
    "L’ultimo giocatore che volevamo prendere ha preferito il campionato vietnamita.",
    "Stavamo per chiudere… ma poi è uscito un nuovo iPhone e abbiamo dovuto fare una scelta.",
    "Il mercato è pieno di opportunità… per gli altri.",
    "Dobbiamo prima vendere un abbonamento Platinum per finanziare l’acquisto.",
    "Ci hanno detto che esiste il fair play finanziario. Siamo rimasti scioccati.",
    "Il presidente ci ha dato il via libera… per comprare nuove divise, non un giocatore.",
    "Abbiamo quasi chiuso, poi ci siamo ricordati che dobbiamo ancora pagare il pullman della trasferta.",
    "Il nostro scout ha trovato il giocatore perfetto… purtroppo gioca a padel.",
    "Abbiamo investito tutto nel catering della sala VIP.",
    "Il nostro obiettivo è rinforzare la squadra… il prossimo anno.",
    "Dobbiamo prima trovare un giocatore che paghi per giocare.",
    "Il mercato è complicato, proprio come il nostro bilancio.",
    "Ci serve tempo per decidere… circa 10 anni.",
    "Abbiamo contattato un top player, ma ha detto che preferisce stare in panchina altrove.",
    "Il nostro GM ha lasciato il telefono in modalità aereo e non ha ricevuto le risposte.",
    "Abbiamo fatto un'offerta seria… purtroppo era troppo seria per il nostro budget.",
    "Siamo stati vicinissimi alla firma, poi il giocatore ha scoperto che il nostro sponsor principale è un ristorante di sushi.",
    "Stiamo aspettando un segnale dal cielo… ma non è ancora arrivato.",
    "Il giocatore era convinto… poi ha visto il meteo di Pesaro d’inverno.",
    "Ci servono rinforzi, ma prima dobbiamo pagare l'ultimo che abbiamo preso.",
    "Abbiamo quasi chiuso, ma poi il giocatore ha controllato il nostro record in classifica.",
    "Ci piace prendere tempo, perché il tempo è gratis.",
    "Stavamo per firmare, ma poi ci siamo accorti che il contratto era ancora scritto in lire.",
    "Abbiamo finito i soldi perché ci siamo fatti fare il parquet nuovo.",
    "Avevamo trovato il giocatore perfetto, ma non sapeva giocare a basket.",
    "L'allenatore ha chiesto un rinforzo, ma il GM ha capito ‘un rinfresco’ e ha ordinato pizzette.",
    "Eravamo pronti, ma poi abbiamo realizzato che avevamo già un roster di 12 persone. Peccato siano tutti infortunati.",
    "Il nostro budget non permette errori, quindi preferiamo non fare nulla.",
    "Abbiamo quasi chiuso con un talento emergente… poi sua mamma ha detto di no.",
    "Siamo in trattativa avanzata con un campione NBA… su NBA 2K.",
    "Abbiamo scoperto all’ultimo che il giocatore che volevamo ingaggiare non esiste.",
    "Stavamo per firmare, ma il giocatore ci ha chiesto uno stipendio. Strano.",
    "Il mercato è in movimento… noi meno.",
    "Avevamo trovato il rinforzo perfetto, ma poi ci ha chiesto se doveva essere pagato.",
    "Il presidente ha detto che possiamo comprare un giocatore, ma solo se porta il suo pranzo da casa.",
    "Il GM ha chiesto aiuto a ChatGPT, e questa è la risposta che ha ricevuto.",
    "Ci manca solo la firma… e il budget… e l’ok del presidente.",
    "Il nostro piano mercato prevede di guardare gli altri prendere i giocatori e sperare in un miracolo.",
    "Abbiamo finito i soldi per colpa delle bollette della palestra.",
    "Non compriamo nessuno perché crediamo nello sviluppo interno… anche se i nostri giovani hanno 38 anni.",
    "Il nostro obiettivo è lottare per i playoff. L'anno prossimo. Forse.",
    "Il nostro scout ha trovato il giocatore perfetto, ma poi ha scoperto che giocava a rugby.",
    "Il giocatore ha accettato, ma poi ha scoperto che il nostro sponsor principale è una pizzeria.",
    "Avevamo il giocatore, poi ha chiesto dove avrebbe vissuto e gli abbiamo mostrato il nostro Airbnb condiviso con la mascotte.",
    "Abbiamo deciso di monitorare il mercato fino al 2030.",
];

function generaScusa() {
    const indice = Math.floor(Math.random() * scuse.length);
    document.getElementById("scusa").textContent = scuse[indice];
}
