const scuse = [
    "Abbiamo monitorato talmente tanto il mercato che ormai ci chiamano Netflix.",
    "Stiamo ancora aspettando che il giocatore risponda su WhatsApp… doppia spunta grigia dal 2023.",
    "Abbiamo trovato il giocatore perfetto, ma aspettiamo che calino i prezzi del Black Friday.",
    "La nostra strategia è aspettare che i giocatori migliori si stufino di aspettare offerte migliori.",
    "Stiamo monitorando il mercato così tanto che ci hanno mandato la bolletta della luce per lo streaming.",
    "Ci siamo quasi… stiamo per chiudere… ma chiudere cosa, esattamente?",
    "Abbiamo ricevuto un’offerta incredibile! Peccato fosse per vendere pentole, non un giocatore.",
    "Il GM sta aspettando il segnale giusto… tipo un meteorite che gli scriva 'compra ora' nel cielo.",
    "Dicono che la pazienza è una virtù. Peccato che nel basket si giochi a tempo.",
    "Abbiamo mandato un emissario in missione segreta per scoprire il mercato… non è più tornato.",
    "Abbiamo quasi chiuso, poi il presidente ha visto il prezzo e ha chiuso il portafoglio.",
    "Il giocatore era pronto a firmare, poi ha letto il nostro record in classifica.",
    "Abbiamo trovato un super talento! Solo che ha 42 anni e gioca ancora a calcetto con gli amici.",
    "Dicono che stiamo monitorando il mercato… in realtà stiamo solo aggiornando Twitter.",
    "Ci piace guardare il mercato come si guarda un bel tramonto: senza fare nulla.",
    "Monitoriamo il mercato con la stessa intensità con cui si guarda una pizza cuocere in forno.",
    "Il mercato è come la dieta: partiamo motivati e finiamo con un panino in mano senza sapere come.",
    "Abbiamo chiesto a ChatGPT di trovarci un giocatore… ci ha consigliato Michael Jordan.",
    "Il nostro scout ha visto un gran talento… ma poi ha scoperto che era un tifoso in tribuna.",
    "Siamo rimasti senza WiFi e non possiamo più monitorare il mercato.",
    "Il giocatore ha accettato, ma poi ha scoperto che il nostro stipendio include solo buoni pasto.",
    "Abbiamo mandato un fax per chiudere il contratto… peccato che sia il 2025 e il fax non esista più.",
    "L’obiettivo della società è chiaro: fare finta di cercare, ma senza mai comprare nessuno.",
    "Il nostro budget è come la dieta dopo Natale: esiste solo sulla carta.",
    "Abbiamo quasi firmato… poi ci siamo resi conto che il nostro GM stava contrattando con un influencer di TikTok.",
    "Il mercato si muove veloce, noi invece siamo fermi come una statua di marmo.",
    "Abbiamo offerto un contratto incredibile! Peccato che il giocatore volesse anche essere pagato.",
    "Il presidente ha chiesto un profilo esperto. Gli abbiamo trovato un ex giocatore… del 1945.",
    "Ci hanno proposto un grande talento, ma il presidente ha detto che 'aspettiamo un attimo'. Era ottobre.",
    "Abbiamo monitorato il mercato così tanto che ci hanno assunto come revisori finanziari.",
    "Il nostro GM è molto attivo… nel farsi offrire aperitivi dai procuratori.",
    "Il giocatore ha detto di sì, ma poi ha scoperto che il nostro sponsor principale vende prosciutti e lui è musulmano e non può mangiarli.",
    "Abbiamo quasi chiuso un colpo, poi abbiamo realizzato che il nostro scouting era basato su Wikipedia.",
    "Ci stiamo concentrando su obiettivi specifici… tipo aspettare la fine della stagione senza fare niente.",
    "Stiamo monitorando così bene il mercato che abbiamo perso di vista la classifica.",
    "La nostra strategia è chiara: monitoriamo il mercato per così tanto tempo che i giocatori ci dimenticano.",
    "Il GM era pronto a firmare… poi ha deciso di riflettere per un altro paio di mesi.",
    "Abbiamo trovato il profilo giusto, ma il presidente ha detto che aspettiamo i saldi estivi.",
];

function generaScusa() {
    const indice = Math.floor(Math.random() * scuse.length);
    document.getElementById("scusa").textContent = scuse[indice];
}
